### ISSUE TITLE
Not installable with current versions of main package

### ISSUE THREAD

**Issue by gndk** [DaveLiddament/phpstan-php-language-extensions#12]
```
  Problem 1
    - Root composer.json requires dave-liddament/phpstan-php-language-extensions 0.2.0 -> satisfiable by dave-liddament/phpstan-php-language-extensions[0.2.0].
    - dave-liddament/phpstan-php-language-extensions 0.2.0 requires dave-liddament/php-language-extensions ^0.2.1 -> found dave-liddament/php-language-extensions[0.2.1] but it conflicts with your root composer.json require (0.4.0).
```

Is this on purpose because this package isn't ready yet, or maybe an oversight?

**Comment by DaveLiddament** [comment]
@gndk Sorry about that. I'm still working on #11 I thought it was finished, but realised that the attribute processing was not correct. I hope to finish it off in the next few weeks. I'll ping you on here when it's released.

**Comment by gndk** [comment]
Ok, thanks for the quick reply! Will use the older version until then :)
